### PR TITLE
MTASS dataset preparation

### PR DESCRIPTION
**Pull request by MasaTate**
Hi, naba !
I liked your repository, and added another dataset preparation code !

[MTASS](https://paperswithcode.com/dataset/mtass) is similar to MUSDB dataset, but it contains three types of audio signals.(speech, music, noise)

I didn't trained your model on MTASS because of time limitation, but I hope my contribution will help in some way.
I'll be glad if you take a look !

### CODE REVIEW

**Comment by naba89** [comment]
Hi @MasaTate 

Thanks for the PR, and this would be a really good addition to the repository. 
I have a few questions/suggestions:
- Did you test the scripts in your local system? 
- What is the folder structure after the preparation of the MTASS dataset? 
- Does the [SeparationDataset](https://github.com/MasaTate/2022-iSeparate/blob/main/iSeparate/datasets/sep_dataset.py#L76) need to be modified for using the MTASS dataset?
- Is there a small subset version of the dataset that could be downloaded for running tests in GitHub workflows?
- Could you add a test to [test_2_datasets.py](https://github.com/MasaTate/2022-iSeparate/blob/main/tests/test_2_datasets.py) for MTASS? If no sample version is available for download, could you create dummy data in the same format/folder structure and create the test?

I know I have made a lot of requests and if it is difficult for you, I can try doing those eventually before I merge it.

**Comment by naba89** [comment]
Since this is a WIP, and for the purpose of the lesson, I will merge it into a separate branch, which can later be merged into the main branch once we have verified it's working.

**Comment by MasaTate** [comment]
@naba89 
Thank you for checking my pull request!
Here is the answers to your questions.

- Did you test the scripts in your local system?
→ Yes, but fragmentally. Not tested whole pipeline. So, I will do that.
- What is the folder structure after the preparation of the MTASS dataset?
↓by default

-MTASS
--data_aishell
--DSD100
--datasets (DNS-Challenge)

-MTASS-wav
--music_data
--noise_data
--speech_data
--train
---mixture
----mixture0
-----mixture0.wav
----mixture1
...
----mixture999 (the number depends on the amount of data)
---music
---noise
---speech
--test
...

- Is there a small subset version of the dataset that could be downloaded for running tests in GitHub workflows?
→ There is no small subset version because we have to combine 3 datasets by ourselves locally.

- Does the [SeparationDataset](https://github.com/MasaTate/2022-iSeparate/blob/main/iSeparate/datasets/sep_dataset.py#L76) need to be modified for using the MTASS dataset?
→ I think so. But I would appreciate it if you could do this. Because I don't fully understand the other code and it will take me long time.
- Could you add a test to [test_2_datasets.py](https://github.com/MasaTate/2022-iSeparate/blob/main/tests/test_2_datasets.py) for MTASS? If no sample version is available for download, could you create dummy data in the same format/folder structure and create the test?
→ I can create dummy data, but I would appreciate it if you could create test code. Because I don't fully understand the other code well and it will take me long time.

**Comment by naba89** [comment]
Hi @MasaTate,

Thanks for the detailed explanations. Understood about the SeparationDataset and adding tests part, will do that myself.

Can I request you to do one more thing, I think should not be too difficult.
The following modification to the folder structure:
```
train
-mixture0
--mixture.wav
--music.wav
--speech.wav
--noise.wav
-mixture1
--...
test
-mixture100
--mixture.wav
--music.wav
--speech.wav
--noise.wav
-mixture101
--...
```

Basically, add all the mixing source wav files along with the mixture wav for each mixture folder under the train/test directory.
This will make it easier to integrate into the data-loading code with minimal modifications.

Also, could you ensure that there is no overlap between the files used for train and those used for test, even if randomly sampling, sample without replacement?

Let me know if anything is not clear.

**Comment by MasaTate** [comment]
Hi, @naba89 !
Thank you for your instruction.
I created another branch from `integrate-mtass` named `modify_mtass` and I modified as you said.
So, I want to make another pull request, but it seems that I don't have an access right to push.
My command line↓
```
(base) masatate@ce206-gpu1:~/MediaComputing/2022-iSeparate$ git branch
  integrate-mtass
  main
* modify_mtass
(base) masatate@ce206-gpu1:~/MediaComputing/2022-iSeparate$ git push origin modify_mtass
ERROR: Permission to media-comp/2022-iSeparate.git denied to MasaTate.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

So, could you please allow me to push to remote repository ? (or this should be asked to sensei?)

**Pull request merged**
